#!/usr/bin/env python3
"""Exercise rail review rebuild, resume, selected rerun, and corruption detection."""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def invoke(archive, output, *options):
    return subprocess.run([sys.executable, "tools/transport/task-084-v2-rail.py", "--archive", str(archive), "--output", str(output), *options], text=True, capture_output=True)


def run(archive):
    parent = Path(tempfile.gettempdir()).resolve()
    temp = Path(tempfile.mkdtemp(prefix="travelassist-task084-v2-", dir=parent)).resolve()
    if temp.parent != parent or not temp.name.startswith("travelassist-task084-v2-"):
        raise RuntimeError("UNSAFE_SELFTEST_TEMP_PATH")
    output = temp / "rail"
    try:
        first = invoke(archive, output)
        assert first.returncode == 0, first.stderr
        baseline = (output / "manifest.json").read_bytes()
        resumed = invoke(archive, output)
        assert resumed.returncode == 0, resumed.stderr
        assert (output / "manifest.json").read_bytes() == baseline
        selected = invoke(archive, output, "--batch", "11", "--rebuild")
        assert selected.returncode == 0, selected.stderr
        assert (output / "manifest.json").read_bytes() == baseline
        corrupt = output / "batches" / "batch-0001.jsonl"
        corrupt.write_bytes(corrupt.read_bytes() + b"{}\n")
        failed = invoke(archive, output)
        assert failed.returncode != 0 and "CORRUPTED_V2_ARTIFACT" in failed.stderr, failed.stderr
        summary = json.loads(first.stdout)
        print(json.dumps({"candidateComponents": summary["candidateComponents"], "resume": "PASS", "selectedBatch11Rerun": "PASS", "corruptionDetection": "PASS"}))
    finally:
        # Recursive cleanup is limited to the directory generated by this run.
        if temp.parent != parent or not temp.name.startswith("travelassist-task084-v2-"):
            raise RuntimeError("UNSAFE_SELFTEST_CLEANUP_PATH")
        shutil.rmtree(temp)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", required=True)
    run(Path(parser.parse_args().archive))
