// Generated by Supabase CLI from Local public schema. DO NOT EDIT.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      companion_group_members: {
        Row: {
          companion_id: string;
          created_at: string;
          group_id: string;
          owner_user_id: string;
          sort_order: number;
        };
        Insert: {
          companion_id: string;
          created_at?: string;
          group_id: string;
          owner_user_id: string;
          sort_order: number;
        };
        Update: {
          companion_id?: string;
          created_at?: string;
          group_id?: string;
          owner_user_id?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "companion_group_members_companion_owner_fk";
            columns: ["companion_id", "owner_user_id"];
            isOneToOne: false;
            referencedRelation: "companions";
            referencedColumns: ["id", "owner_user_id"];
          },
          {
            foreignKeyName: "companion_group_members_group_owner_fk";
            columns: ["group_id", "owner_user_id"];
            isOneToOne: false;
            referencedRelation: "companion_groups";
            referencedColumns: ["id", "owner_user_id"];
          },
        ];
      };
      companion_groups: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          includes_owner: boolean;
          name: string;
          owner_user_id: string;
          revision: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          includes_owner?: boolean;
          name: string;
          owner_user_id: string;
          revision?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          includes_owner?: boolean;
          name?: string;
          owner_user_id?: string;
          revision?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      companions: {
        Row: {
          age_group_fallback: string | null;
          avatar_path: string | null;
          birth_date: string | null;
          created_at: string;
          display_name: string;
          gender_code: string | null;
          id: string;
          owner_user_id: string;
          relationship_code: string | null;
          relationship_label: string | null;
          revision: number;
          travel_profile: Json;
          updated_at: string;
        };
        Insert: {
          age_group_fallback?: string | null;
          avatar_path?: string | null;
          birth_date?: string | null;
          created_at?: string;
          display_name: string;
          gender_code?: string | null;
          id?: string;
          owner_user_id: string;
          relationship_code?: string | null;
          relationship_label?: string | null;
          revision?: number;
          travel_profile?: Json;
          updated_at?: string;
        };
        Update: {
          age_group_fallback?: string | null;
          avatar_path?: string | null;
          birth_date?: string | null;
          created_at?: string;
          display_name?: string;
          gender_code?: string | null;
          id?: string;
          owner_user_id?: string;
          relationship_code?: string | null;
          relationship_label?: string | null;
          revision?: number;
          travel_profile?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      emergency_contacts: {
        Row: {
          country_code: string | null;
          created_at: string;
          email: string | null;
          id: string;
          name: string;
          note: string | null;
          phone_e164: string;
          relationship: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          country_code?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          name: string;
          note?: string | null;
          phone_e164: string;
          relationship: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          country_code?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          name?: string;
          note?: string | null;
          phone_e164?: string;
          relationship?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      profile_settings: {
        Row: {
          created_at: string;
          currency_code: string | null;
          distance_unit: string | null;
          locale: string | null;
          region_code: string | null;
          temperature_unit: string | null;
          time_format: string | null;
          timezone: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          currency_code?: string | null;
          distance_unit?: string | null;
          locale?: string | null;
          region_code?: string | null;
          temperature_unit?: string | null;
          time_format?: string | null;
          timezone?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          currency_code?: string | null;
          distance_unit?: string | null;
          locale?: string | null;
          region_code?: string | null;
          temperature_unit?: string | null;
          time_format?: string | null;
          timezone?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_path: string | null;
          birth_date: string | null;
          created_at: string;
          display_name: string | null;
          full_name: string | null;
          gender_code: string | null;
          id: string;
          residence_city: string | null;
          residence_country_code: string | null;
          updated_at: string;
        };
        Insert: {
          avatar_path?: string | null;
          birth_date?: string | null;
          created_at?: string;
          display_name?: string | null;
          full_name?: string | null;
          gender_code?: string | null;
          id: string;
          residence_city?: string | null;
          residence_country_code?: string | null;
          updated_at?: string;
        };
        Update: {
          avatar_path?: string | null;
          birth_date?: string | null;
          created_at?: string;
          display_name?: string | null;
          full_name?: string | null;
          gender_code?: string | null;
          id?: string;
          residence_city?: string | null;
          residence_country_code?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      travel_preferences: {
        Row: {
          created_at: string;
          owner_user_id: string;
          payload: Json;
          revision: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          owner_user_id: string;
          payload?: Json;
          revision?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          owner_user_id?: string;
          payload?: Json;
          revision?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      trip_library_records: {
        Row: {
          canonical_trip_id: string | null;
          created_at: string;
          creation_intent_hash: string | null;
          creation_key: string;
          draft_facts: Json;
          frozen_at: string | null;
          id: string;
          library_state: string;
          owner_user_id: string;
          party_snapshot: Json;
          plan_snapshot: Json | null;
          preference_override_patch: Json;
          preference_snapshot: Json;
          preference_source_revision: number;
          storage_revision: number;
          updated_at: string;
          wizard_progress: Json;
        };
        Insert: {
          canonical_trip_id?: string | null;
          created_at?: string;
          creation_intent_hash?: string | null;
          creation_key: string;
          draft_facts: Json;
          frozen_at?: string | null;
          id?: string;
          library_state?: string;
          owner_user_id: string;
          party_snapshot: Json;
          plan_snapshot?: Json | null;
          preference_override_patch?: Json;
          preference_snapshot: Json;
          preference_source_revision: number;
          storage_revision?: number;
          updated_at?: string;
          wizard_progress: Json;
        };
        Update: {
          canonical_trip_id?: string | null;
          created_at?: string;
          creation_intent_hash?: string | null;
          creation_key?: string;
          draft_facts?: Json;
          frozen_at?: string | null;
          id?: string;
          library_state?: string;
          owner_user_id?: string;
          party_snapshot?: Json;
          plan_snapshot?: Json | null;
          preference_override_patch?: Json;
          preference_snapshot?: Json;
          preference_source_revision?: number;
          storage_revision?: number;
          updated_at?: string;
          wizard_progress?: Json;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_companion_travel_profile_v1: {
        Args: { payload: Json };
        Returns: boolean;
      };
      is_travel_preference_v1: { Args: { payload: Json }; Returns: boolean };
      is_trip_library_envelope_v1: {
        Args: { max_bytes: number; payload: Json; version_key: string };
        Returns: boolean;
      };
      is_trip_party_snapshot_v1: { Args: { payload: Json }; Returns: boolean };
      mutate_companion_group_v1: {
        Args: {
          p_action: string;
          p_expected_revision?: number;
          p_id?: string;
          p_includes_owner?: boolean;
          p_member_ids?: string[];
          p_name?: string;
        };
        Returns: Json;
      };
      mutate_companion_v1: {
        Args: {
          p_action: string;
          p_expected_revision?: number;
          p_id?: string;
          p_input?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
