import { spawnSync } from "node:child_process";
import { readFile, writeFile, rename, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const root = fileURLToPath(new URL("../../", import.meta.url));
const require = createRequire(import.meta.url);

export const commands = Object.freeze({
  start: ["start"],
  stop: ["stop"],
  status: ["status", "--output", "json"],
  reset: ["db", "reset", "--local", "--yes"],
  types: ["gen", "types", "typescript", "--local", "--schema", "public"],
});

export function commandArgs(argv) {
  if (argv.length !== 1 || !Object.hasOwn(commands, argv[0])) {
    throw new Error(
      "Use db:start/stop/status/reset/types without extra flags.",
    );
  }
  return [...commands[argv[0]]];
}

// Do not forward cloud credentials, PG variables, or arbitrary CLI overrides.
export function localEnv(source) {
  const allowed =
    /^(PATH|PATHEXT|SYSTEMROOT|WINDIR|TEMP|TMP|USERPROFILE|APPDATA|LOCALAPPDATA|PROGRAMDATA|PROGRAMFILES|PROGRAMFILES\(X86\)|COMSPEC|LANG|LC_ALL|DOCKER_HOST|DOCKER_CONTEXT)$/i;
  const env = Object.fromEntries(
    Object.entries(source)
      .filter(([name]) => allowed.test(name))
      .map(([name, value]) => [name.toUpperCase(), value]),
  );
  return { ...env, SUPABASE_TELEMETRY_DISABLED: "1", DO_NOT_TRACK: "1" };
}

export function assertLocalEndpoint(endpoint) {
  if (
    !/^npipe:\/\/\/\/\.\/pipe\/[\w.-]+$/.test(endpoint) &&
    !/^unix:\/\/\/(?!\/)[^\s]+$/.test(endpoint)
  ) {
    throw new Error("Only a local Docker socket/named pipe is permitted.");
  }
  return endpoint;
}

function run(file, args, env, timeout = 120_000) {
  return spawnSync(file, args, {
    cwd: root,
    env,
    encoding: "utf8",
    windowsHide: true,
    shell: false,
    timeout,
    maxBuffer: 16 * 1024 * 1024,
  });
}

function dockerPreflight(env) {
  if (run("docker", ["--version"], env).status !== 0) {
    throw new Error("DB runtime verification: Blocked — Docker unavailable");
  }
  let endpoint = env.DOCKER_HOST;
  if (!endpoint || env.DOCKER_CONTEXT) {
    const context = run("docker", ["context", "inspect"], env);
    if (context.status !== 0)
      throw new Error("Docker context inspection failed.");
    try {
      endpoint = JSON.parse(context.stdout)[0].Endpoints.docker.Host;
    } catch {
      throw new Error("Docker context did not provide a local endpoint.");
    }
  }
  assertLocalEndpoint(endpoint ?? "");
  delete env.DOCKER_CONTEXT;
  env.DOCKER_HOST = endpoint;
  if (
    run("docker", ["info", "--format", "{{.ServerVersion}}"], env).status !== 0
  ) {
    throw new Error(
      "DB runtime verification: Blocked — local Docker daemon unavailable",
    );
  }
}

export function publicStatus(raw) {
  let data;
  try {
    data = JSON.parse(raw);
    if (!data || typeof data !== "object" || Array.isArray(data))
      throw new Error();
  } catch {
    throw new Error("Invalid CLI status; raw output withheld.");
  }
  const output = {};
  for (const key of ["API_URL", "STUDIO_URL", "INBUCKET_URL"]) {
    if (!data[key]) continue;
    let url;
    try {
      url = new URL(data[key]);
    } catch {
      throw new Error("Invalid local service URL; status withheld.");
    }
    if (
      !["localhost", "127.0.0.1", "[::1]"].includes(url.hostname) ||
      !["http:", "https:"].includes(url.protocol) ||
      url.username ||
      url.password ||
      url.search ||
      url.hash
    )
      throw new Error("Unexpected local service URL; status withheld.");
    output[key] = url.href;
  }
  if (!Object.keys(output).length)
    throw new Error("No recognized local service URLs; status withheld.");
  return output;
}

export async function writeGeneratedTypes(raw, target) {
  if (!/export type Database\s*=/.test(raw) || !/public:\s*\{/.test(raw)) {
    throw new Error(
      "CLI did not return database types; existing output preserved.",
    );
  }
  let content;
  try {
    content = await format(
      "// Generated by Supabase CLI from Local public schema. DO NOT EDIT.\n" +
        raw,
      { parser: "typescript" },
    );
  } catch {
    throw new Error("Invalid generated TypeScript; existing output preserved.");
  }
  if ((await readFile(target, "utf8").catch(() => null)) === content) return;
  const temp = `${target}.tmp`;
  try {
    await writeFile(temp, content, { flag: "wx" });
  } catch {
    throw new Error(
      "Cannot create types staging file; existing output preserved.",
    );
  }
  try {
    await rename(temp, target);
  } finally {
    await rm(temp, { force: true });
  }
}

export async function main(argv) {
  const args = commandArgs(argv);
  const env = localEnv(process.env);
  dockerPreflight(env);
  const pkg = require.resolve("supabase/package.json");
  const { bin } = JSON.parse(await readFile(pkg, "utf8"));
  const cli = resolve(dirname(pkg), bin.supabase);
  // CLI output can contain credentials, including on failures. Never forward it.
  const result = run(process.execPath, [cli, ...args], env, 20 * 60_000);
  if (result.status !== 0) {
    throw new Error(
      `Local Supabase ${argv[0]} failed; raw CLI output withheld for credential safety.`,
    );
  }
  if (argv[0] === "status")
    console.log(JSON.stringify(publicStatus(result.stdout), null, 2));
  if (argv[0] === "types") {
    await writeGeneratedTypes(
      result.stdout,
      resolve(root, "src/types/database.generated.ts"),
    );
  }
  console.log(`Local Supabase ${argv[0]} succeeded.`);
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
